const tagColors = {
  Python: "#cdeac0",
  Java: "#EFDFDA",
  Javascript: "#E8DFEE",
  React: "#D4E6EE",
  CSS: "#d7e3fc",
  C: "#e2e2e2",
  Docker: "#fcf4dd",
  Postman: "#fce1e4",
  R: "#CAE7E3",
  EDA: "#E7CBA9",
  HTML: "#EEBAB2",
  JavaScript: "#F5F3E7",
  GeoSpatial: "#F5E2E4",
  SQL: "#F7F6CF",
  AWS: "#C9DFEC",
  "Healthcare Data Analysis": "#E3E4FA",
  Excel: "#B3D9D9",
  "Web Scraping": "#F3E3C3",
  ReactJS: "#B3C8CF",
  NodeJS: "#DBDFAA",
  API: "#F8E8EE",
  "Blockchain data": "#BCCDCF",
  "Neural Network": "#B5C0D0",
  Classification: "#F5E8DD",
  Pipeline: "#DFCCFB",
  "Data QA": "#C4C1A4",
  Airflow: "#F9F9E0",
  "Apache Spark": "#dfe7fd", //"#E7E8D8",
  Solana: "#d8e2dc",
  "Machine Learning": "#bee1e6",
  DNN: "#e3d5ca",
  "Neural Networks": "#f5efff",
  TensorFlow: "#fcd5ce",
  Keras: "#f9e5d8",
  CNN: "#dcedc1",
  "Image Processing": "#f2ebfb",
  Segmentation: "#c2e2ea",
  "Data Cleaning": "#FFEBD4",
  RDBMS: "#bde0fe",
  JSON: "#dbcdf0",
  MapReduce: "#afd3ed",
  Hadoop: "#9fbdf5",
  "GeoSpatial Data": "#eff7f6",
  "Spatial Analysis": "#fad2e1",
  "Hypothesis Testing": "#DBEDDC",
  Clustering: "#efcfe3",
  ggplot: "#eec6ca",
  Packages: "#bad7f2",
  YOLO: "#ded6d1",
  RNN: "#a7bed3",
  Tableau: "#d2d2ff",
};
export default tagColors;
